version: "3.8"
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: postgres:16
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
        - db.env
    ports:
      - "15432:5432"

  app:
    container_name: "app"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - "db"
    command: /bin/bash -c "npm run start:prod"

volumes:
  database:
