version: "3.8"
services:
  rabbit:
    container_name: "rabbit"
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - main
  db:
    container_name: "db"
    image: postgres:16
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
        - db.env
    ports:
      - "15432:5432"
    networks:
      - main

  webapp:
    container_name: "webapp"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=db
      - RABBITMQ_URL=amqp://rabbit
    env_file:
      - app.env
    links:
      - "db"
      - "rabbit"
    networks:
      - main
    command: /bin/bash -c "npm run app:start:prod"

  bot:
    container_name: "bot"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    env_file:
        - app.env
    links:
      - "db"
      - "rabbit"
    networks:
      - main
    command: /bin/bash -c "npm run bot:start:prod"

volumes:
  database:

networks:
  main:
    name: main
